### ISSUE TITLE
[bug]: "Quick Connect" and "RPC Connect" URLs do not match - they are supposed to be the same.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/bitcoind-startos#111]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.5

### Browser

Firefox

### Browser Version

108.1

### Current Behavior

Two different addresses:

Properties:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/45926711/209406858-bd64d696-1a91-43cd-9fd3-4a401d89b15e.png">

Interfaces:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/45926711/209406868-7d83e4fb-efdc-4230-9286-a8cac5edb867.png">

### Expected Behavior

They should match

### Steps to Reproduce

Install bitcoin core, check properties and interfaces.

**Comment by remcoros** [comment]
This had me confused initially too, but the addresses are the same.

The URL in Properties contains the password (look closely, the format is btcstandup:// <user> : <password> @ <hostname>

**Comment by Dominion5254** [comment]
Agreed with @remcoros
