### ISSUE TITLE
[feat]: add reindex-chainstate action

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/bitcoind-startos#71]

**Comment by MattDHill** [comment]
How is this different from the "Reindex Blockchain" action?

**Comment by chrisguida** [comment]
Reindex Blockchain calls bitcoind with `--reindex`, while Reindex Chainstate would call bitcoind with `--reindex-chainstate`. The difference is somewhat subtle, but basically reindex-chainstate likely is much faster: https://bitcoin.stackexchange.com/questions/60709/when-should-i-use-reindex-chainstate-and-when-reindex

**Comment by gStart9** [comment]
![embassy-bitcoind-actions-reindex-blockchain-done](https://user-images.githubusercontent.com/106188942/195904916-70b37c30-a28b-49be-afbf-1a32c1cf79f8.jpg)

^This is complete for a while now.  Closing issue.

**Comment by chrisguida** [comment]
Not seeing it?

**Comment by kn0wmad** [comment]
This definitely exists

**Comment by chrisguida** [comment]
It really doesn't xD

**Comment by gStart9** [comment]
My previous comment in this thread is completely wrong!

We had somebody today who needed `-reindex-chainstate`, similar to this:
https://bitcointalk.org/index.php?topic=5493375

*Bump* on needing a `-reindex-chainstate` / `reindex-chainstate=1` action.
